# 数据操作



首先，我们导入`torch`。请注意，虽然它被称为PyTorch，但是代码中使用`torch`而不是`pytorch`

In [3]:
import torch

张量表示一个由数值组成的数组，这个数组可能有多个维度

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过张量的`shape`属性来访问张量（沿每个轴的长度）的*形状*
和张量中元素的总数

In [5]:
x.shape# 一维向量

torch.Size([12])

In [6]:
x.numel()#number of elements（元素总数）

12

要想改变一个张量的形状而不改变元素数量和元素值，可以调用`reshape`函数

In [7]:
X = x.reshape(3, 4)#3行4列
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0、全1、其他常量，或者从特定分布中随机采样的数字

In [8]:
torch.zeros((2, 3, 4))# 3维向量：2个3行4列的矩阵，值全0

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))# 3维向量：2个3行4列的矩阵，值全1

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(3, 4)# 2维矩阵，3行4列，random + normal（正态分布随机数）

tensor([[-0.0135,  0.0665,  0.0912,  0.3212],
        [ 1.4653,  0.1843, -1.6995, -0.3036],
        [ 1.7646,  1.0450,  0.2457, -0.7732]])

通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值

In [16]:
a = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])# tensor是张量，可以有任意维度
print(a)
print(a.shape) # 这边创建的是2维的3行4列
b = torch.tensor([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]])
print(b)
print(b.shape)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
torch.Size([3, 4])
tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])
torch.Size([1, 3, 4])


常见的标准算术运算符（`+`、`-`、`*`、`/`和`**`）都可以被升级为按元素运算

In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

“按元素”方式可以应用更多的计算

In [18]:
torch.exp(x)# 指数

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

我们也可以把多个张量*连结*（concatenate）在一起

In [27]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))# dtype指定float32类型
print(f'x = {X}')
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(f'y = {Y}')
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)# dim=0 上下堆叠
# dim = 1 左右并排
# dim = 2 前后叠放
# 试试3维
X = torch.arange(24, dtype=torch.float32).reshape((2,3,4))
print(f'3维 x = {X}')
Y = torch.tensor([
    [[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]],
    [[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]
])
print(f'3维 y = {Y}')
# 从结果可以看出
# dim = 0 是矩阵堆叠 把y 的两个矩阵放到x的两个矩阵下面
#   [
#       X的第1个矩阵,  # [[0,1,2,3], [4,5,6,7], [8,9,10,11]]
#       X的第2个矩阵,  # [[12,13,14,15], [16,17,18,19], [20,21,22,23]]
#       Y的第1个矩阵,  # [[2,1,4,3], [1,2,3,4], [4,3,2,1]]
#       Y的第2个矩阵   # [[2,1,4,3], [1,2,3,4], [4,3,2,1]]
#   ]
print(f'dim = 0, {torch.cat((X, Y), dim=0)}')
# dim = 1 是行合并
# 结构：
# [
#     [  # 第1个矩阵
#         X的第1行: [0,1,2,3],
#         X的第2行: [4,5,6,7],
#         X的第3行: [8,9,10,11],
#         Y的第1行: [2,1,4,3],  # ← 新增的行
#         Y的第2行: [1,2,3,4],  # ← 新增的行
#         Y的第3行: [4,3,2,1]   # ← 新增的行
#     ],
#     [  # 第2个矩阵
#         X的第1行: [12,13,14,15],
#         X的第2行: [16,17,18,19],
#         X的第3行: [20,21,22,23],
#         Y的第1行: [2,1,4,3],  # ← 新增的行
#         Y的第2行: [1,2,3,4],  # ← 新增的行
#         Y的第3行: [4,3,2,1]   # ← 新增的行
#     ]
# ]
print(f'dim = 1, {torch.cat((X, Y), dim=1)}')
# dim = 2 是列合并
# 结构：
# [
#     [  # 第1个矩阵
#         [0,1,2,3, 2,1,4,3],  # X第1行 + Y第1行
#         [4,5,6,7, 1,2,3,4],  # X第2行 + Y第2行
#         [8,9,10,11, 4,3,2,1] # X第3行 + Y第3行
#     ],
#     [  # 第2个矩阵
#         [12,13,14,15, 2,1,4,3],  # X第1行 + Y第1行
#         [16,17,18,19, 1,2,3,4],  # X第2行 + Y第2行
#         [20,21,22,23, 4,3,2,1]   # X第3行 + Y第3行
#     ]
# ]
print(f'dim = 2, {torch.cat((X, Y), dim=2)}')

x = tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
y = tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
3维 x = tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
3维 y = tensor([[[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]],

        [[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]])
dim = 0, tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]],

        [[ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]],

        [[ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]])
dim = 1, tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.

通过*逻辑运算符*构建二元张量

In [41]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和，会产生一个单元素张量

In [29]:
X.sum()

tensor(276.)

即使形状不同，我们仍然可以通过调用
*广播机制*（broadcasting mechanism）来执行按元素操作

In [49]:
a = torch.arange(6).reshape((2, 3, 1)) 
b = torch.arange(4).reshape((2, 1, 2))
a, b

(tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]]]),
 tensor([[[0, 1]],
 
         [[2, 3]]]))

In [50]:
a + b # a 和 b 都扩展成 3 * 2
# 0 0  + 0 1
# 1 1  + 0 1
# 2 2  + 0 1

tensor([[[0, 1],
         [1, 2],
         [2, 3]],

        [[5, 6],
         [6, 7],
         [7, 8]]])

可以用`[-1]`选择最后一个元素，可以用`[1:3]`选择第二个和第三个元素

In [34]:
X[-1], X[1:3]

(tensor([[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]),
 tensor([[[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]))

除读取外，我们还可以通过指定索引来将元素写入矩阵

In [35]:
X[1, 2] = 9
X

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [ 9.,  9.,  9.,  9.]]])

为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值

In [36]:
print(X)
X[0:2, :] = 12 # 把0行到1行，和所有的列选中
X

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [ 9.,  9.,  9.,  9.]]])


tensor([[[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [12., 12., 12., 12.]],

        [[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [12., 12., 12., 12.]]])

运行一些操作可能会导致为新结果分配内存

In [37]:
before = id(Y) # 获取Y的内存地址
Y = Y + X
id(Y) == before # 现在的内存地址和之前的不同了

False

执行原地操作

In [38]:
Z = torch.zeros_like(Y) # 创建一个与输入张量形状相同、但所有元素都为0的新张量
print('id(Z):', id(Z))
Z[:] = X + Y 
print('id(Z):', id(Z))

id(Z): 2579696428592
id(Z): 2579696428592


如果在后续计算中没有重复使用`X`，
我们也可以使用`X[:] = X + Y`或`X += Y`来减少操作的内存开销

In [22]:
before = id(X)
X += Y
id(X) == before

True

转换为NumPy张量（`ndarray`）

In [23]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为Python标量

In [40]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [1]:
import torch

# 3维张量 A: (2, 1, 4)
A = torch.tensor([
    [[1, 2, 3, 4]],           # 第一个2D矩阵
    [[5, 6, 7, 8]]            # 第二个2D矩阵
])  # 形状: (2, 1, 4)

# 3维张量 B: (1, 3, 1)
B = torch.tensor([
    [[10], [20], [30]]        # 3个行向量
])  # 形状: (1, 3, 1)

print("A形状:", A.shape)
print("B形状:", B.shape)

# 广播操作
result = A + B
print("结果形状:", result.shape)
print("广播结果:")
print(result)

A形状: torch.Size([2, 1, 4])
B形状: torch.Size([1, 3, 1])
结果形状: torch.Size([2, 3, 4])
广播结果:
tensor([[[11, 12, 13, 14],
         [21, 22, 23, 24],
         [31, 32, 33, 34]],

        [[15, 16, 17, 18],
         [25, 26, 27, 28],
         [35, 36, 37, 38]]])
